spring:
  ai:
    retry:
      max-attempts: 1
    openai:
      api-key: "enter-key-here"
      chat:
        options:
          model: "gpt-4o-mini"
          temperature: 0.5
  datasource:
    driver-class-name: org.postgresql.Driver
    password: abc123
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update # makes schema changes to the DB to match hibernate entities

dgs:
  graphql:
    schema-locations:
      - classpath:graphql/schema.graphqls
