CREATE TABLE IF NOT EXISTS test.ingredient (
                                          id UUID PRIMARY KEY,
                                          name TEXT NOT NULL UNIQUE,
                                          category TEXT
);

INSERT INTO test.ingredient (id, name, category) VALUES
(gen_random_uuid(), 'Olive Oil', 'FAT'),
(gen_random_uuid(), 'Butter', 'FAT'),
(gen_random_uuid(), 'Coconut Oil', 'FAT'),
(gen_random_uuid(), 'Vegetable Oil', 'FAT'),
(gen_random_uuid(), 'Milk', 'DAIRY'),
(gen_random_uuid(), 'Cheese', 'DAIRY'),
(gen_random_uuid(), 'Yogurt', 'DAIRY'),
(gen_random_uuid(), 'Plant Based Milk', 'DAIRY'),
(gen_random_uuid(), 'Chicken', 'PROTEIN'),
(gen_random_uuid(), 'Salmon', 'PROTEIN'),
(gen_random_uuid(), 'Steak', 'PROTEIN'),
(gen_random_uuid(), 'Shrimp', 'PROTEIN'),
(gen_random_uuid(), 'Tilapia', 'PROTEIN'),
(gen_random_uuid(), 'Tofu', 'PROTEIN'),
(gen_random_uuid(), 'Lamb', 'PROTEIN'),
(gen_random_uuid(), 'Tempeh', 'PROTEIN'),
(gen_random_uuid(), 'Beans', 'PROTEIN'),
(gen_random_uuid(), 'Lentils', 'PROTEIN'),
(gen_random_uuid(), 'Chickpeas', 'PROTEIN'),
(gen_random_uuid(), 'Pork', 'PROTEIN'),
(gen_random_uuid(), 'Turkey', 'PROTEIN'),
(gen_random_uuid(), 'Eggs', 'PROTEIN'),
(gen_random_uuid(), 'Bacon', 'PROTEIN'),
(gen_random_uuid(), 'Sausage', 'PROTEIN'),
(gen_random_uuid(), 'Ham', 'PROTEIN'),
(gen_random_uuid(), 'Rice', 'GRAIN'),
(gen_random_uuid(), 'Quinoa', 'GRAIN'),
(gen_random_uuid(), 'Pasta', 'GRAIN'),
(gen_random_uuid(), 'Bread', 'GRAIN'),
(gen_random_uuid(), 'Tortilla', 'GRAIN'),
(gen_random_uuid(), 'Pita', 'GRAIN'),
(gen_random_uuid(), 'Bagel', 'GRAIN'),
(gen_random_uuid(), 'Broccoli', 'VEGETABLE'),
(gen_random_uuid(), 'Spinach', 'VEGETABLE'),
(gen_random_uuid(), 'Kale', 'VEGETABLE'),
(gen_random_uuid(), 'Carrots', 'VEGETABLE'),
(gen_random_uuid(), 'Peppers', 'VEGETABLE'),
(gen_random_uuid(), 'Zucchini', 'VEGETABLE'),
(gen_random_uuid(), 'Squash', 'VEGETABLE'),
(gen_random_uuid(), 'Asparagus', 'VEGETABLE'),
(gen_random_uuid(), 'Brussels Sprouts', 'VEGETABLE'),
(gen_random_uuid(), 'Cabbage', 'VEGETABLE'),
(gen_random_uuid(), 'Cauliflower', 'VEGETABLE'),
(gen_random_uuid(), 'Sweet Potato', 'VEGETABLE'),
(gen_random_uuid(), 'Potato', 'VEGETABLE'),
(gen_random_uuid(), 'Tomato', 'VEGETABLE'),
(gen_random_uuid(), 'Cucumber', 'VEGETABLE'),
(gen_random_uuid(), 'Onion', 'VEGETABLE'),
(gen_random_uuid(), 'Garlic', 'VEGETABLE'),
(gen_random_uuid(), 'Ginger', 'VEGETABLE'),
(gen_random_uuid(), 'Mushrooms', 'VEGETABLE'),
(gen_random_uuid(), 'Apple', 'FRUIT'),
(gen_random_uuid(), 'Orange', 'FRUIT'),
(gen_random_uuid(), 'Banana', 'FRUIT'),
(gen_random_uuid(), 'Strawberry', 'FRUIT'),
(gen_random_uuid(), 'Blueberry', 'FRUIT'),
(gen_random_uuid(), 'Raspberry', 'FRUIT'),
(gen_random_uuid(), 'Blackberry', 'FRUIT'),
(gen_random_uuid(), 'Grape', 'FRUIT'),
(gen_random_uuid(), 'Mango', 'FRUIT'),
(gen_random_uuid(), 'Pineapple', 'FRUIT'),
(gen_random_uuid(), 'Watermelon', 'FRUIT'),
(gen_random_uuid(), 'Cantaloupe', 'FRUIT'),
(gen_random_uuid(), 'Peach', 'FRUIT'),
(gen_random_uuid(), 'Plum', 'FRUIT'),
(gen_random_uuid(), 'Pear', 'FRUIT'),
(gen_random_uuid(), 'Cherry', 'FRUIT'),
(gen_random_uuid(), 'Lemon', 'FRUIT'),
(gen_random_uuid(), 'Lime', 'FRUIT'),
(gen_random_uuid(), 'Grapefruit', 'FRUIT'),
(gen_random_uuid(), 'Coconut', 'FRUIT'),
(gen_random_uuid(), 'Avocado', 'FRUIT'),
(gen_random_uuid(), 'Pomegranate', 'FRUIT'),
(gen_random_uuid(), 'Tangerine', 'FRUIT'),
(gen_random_uuid(), 'Salt', 'HERB_SPICE'),
(gen_random_uuid(), 'Pepper', 'HERB_SPICE'),
(gen_random_uuid(), 'Garlic Powder', 'HERB_SPICE'),
(gen_random_uuid(), 'Onion Powder', 'HERB_SPICE'),
(gen_random_uuid(), 'Paprika', 'HERB_SPICE'),
(gen_random_uuid(), 'Cumin', 'HERB_SPICE'),
(gen_random_uuid(), 'Chili Powder', 'HERB_SPICE'),
(gen_random_uuid(), 'Cayenne', 'HERB_SPICE'),
(gen_random_uuid(), 'Turmeric', 'HERB_SPICE'),
(gen_random_uuid(), 'Ginger', 'HERB_SPICE'),
(gen_random_uuid(), 'Cinnamon', 'HERB_SPICE'),
(gen_random_uuid(), 'Nutmeg', 'HERB_SPICE'),
(gen_random_uuid(), 'Cloves', 'HERB_SPICE'),
(gen_random_uuid(), 'Allspice', 'HERB_SPICE'),
(gen_random_uuid(), 'Coriander', 'HERB_SPICE'),
(gen_random_uuid(), 'Cardamom', 'HERB_SPICE'),
(gen_random_uuid(), 'Fennel', 'HERB_SPICE'),
(gen_random_uuid(), 'Bay Leaf', 'HERB_SPICE'),
(gen_random_uuid(), 'Oregano', 'HERB_SPICE'),
(gen_random_uuid(), 'Thyme', 'HERB_SPICE'),
(gen_random_uuid(), 'Rosemary', 'HERB_SPICE'),
(gen_random_uuid(), 'Sage', 'HERB_SPICE'),
(gen_random_uuid(), 'Parsley', 'HERB_SPICE'),
(gen_random_uuid(), 'Cilantro', 'HERB_SPICE'),
(gen_random_uuid(), 'Dill', 'HERB_SPICE'),
(gen_random_uuid(), 'Mint', 'HERB_SPICE'),
(gen_random_uuid(), 'Basil', 'HERB_SPICE'),
(gen_random_uuid(), 'Chives', 'HERB_SPICE'),
(gen_random_uuid(), 'Tarragon', 'HERB_SPICE'),
(gen_random_uuid(), 'Lemon Grass', 'HERB_SPICE'),
(gen_random_uuid(), 'Lemon Zest', 'HERB_SPICE'),
(gen_random_uuid(), 'Lime Zest', 'HERB_SPICE'),
(gen_random_uuid(), 'Orange Zest', 'HERB_SPICE'),
(gen_random_uuid(), 'Vanilla', 'HERB_SPICE'),
(gen_random_uuid(), 'Soy Sauce', 'SAUCE_CONDIMENT'),
(gen_random_uuid(), 'Teriyaki Sauce', 'SAUCE_CONDIMENT'),
(gen_random_uuid(), 'BBQ Sauce', 'SAUCE_CONDIMENT'),
(gen_random_uuid(), 'Ketchup', 'SAUCE_CONDIMENT'),
(gen_random_uuid(), 'Mustard', 'SAUCE_CONDIMENT'),
(gen_random_uuid(), 'Mayo', 'SAUCE_CONDIMENT'),
(gen_random_uuid(), 'Ranch', 'SAUCE_CONDIMENT'),
(gen_random_uuid(), 'Blue Cheese', 'SAUCE_CONDIMENT'),
(gen_random_uuid(), 'Buffalo Sauce', 'SAUCE_CONDIMENT'),
(gen_random_uuid(), 'Sriracha', 'SAUCE_CONDIMENT'),
(gen_random_uuid(), 'Hot Sauce', 'SAUCE_CONDIMENT'),
(gen_random_uuid(), 'Salsa', 'SAUCE_CONDIMENT'),
(gen_random_uuid(), 'Honey', 'SWEETENER'),
(gen_random_uuid(), 'Maple Syrup', 'SWEETENER'),
(gen_random_uuid(), 'Molasses', 'SWEETENER'),
(gen_random_uuid(), 'Brown Sugar', 'SWEETENER'),
(gen_random_uuid(), 'White Sugar', 'SWEETENER'),
(gen_random_uuid(), 'Powdered Sugar', 'SWEETENER'),
(gen_random_uuid(), 'Flour', 'BAKING_INGREDIENT'),
(gen_random_uuid(), 'Baking Powder', 'BAKING_INGREDIENT'),
(gen_random_uuid(), 'Baking Soda', 'BAKING_INGREDIENT'),
(gen_random_uuid(), 'Yeast', 'BAKING_INGREDIENT'),
(gen_random_uuid(), 'Cornstarch', 'BAKING_INGREDIENT'),
(gen_random_uuid(), 'Almonds', 'NUTS_SEEDS'),
(gen_random_uuid(), 'Walnuts', 'NUTS_SEEDS'),
(gen_random_uuid(), 'Pecans', 'NUTS_SEEDS'),
(gen_random_uuid(), 'Cashews', 'NUTS_SEEDS'),
(gen_random_uuid(), 'Pistachios', 'NUTS_SEEDS'),
(gen_random_uuid(), 'Peanuts', 'NUTS_SEEDS'),
(gen_random_uuid(), 'Hazelnuts', 'NUTS_SEEDS'),
(gen_random_uuid(), 'Macadamia', 'NUTS_SEEDS'),
(gen_random_uuid(), 'Sesame Seeds', 'NUTS_SEEDS'),
(gen_random_uuid(), 'Chia Seeds', 'NUTS_SEEDS'),
(gen_random_uuid(), 'Flaxseeds', 'NUTS_SEEDS'),
(gen_random_uuid(), 'Pumpkin Seeds', 'NUTS_SEEDS'),
(gen_random_uuid(), 'Sunflower Seeds', 'NUTS_SEEDS'),
(gen_random_uuid(), 'Poppy Seeds', 'NUTS_SEEDS'),
(gen_random_uuid(), 'Hemp Seeds', 'NUTS_SEEDS')
ON CONFLICT DO NOTHING;
